version: "3.9"
services:
  mysql:
    build: . #Dockerfileからビルドする
    environment:
      - MYSQL_ROOT_PASSWORD=273393 #コンテナ内のMySQLを起動する際のパスワードを設定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
